name: navika
description: Navika.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.7.2+14

environment:
  sdk: '>=2.18.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  url_strategy: ^0.2.0
  quiver: ^3.1.0
  path_to_regexp: ^0.4.0
  url_launcher: ^6.1.5
  adaptive_navigation: ^0.0.7
  http: ^0.13.5
  location: ^4.4.0
  sliding_up_panel: ^2.0.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_svg: ^1.1.6
  flutter_inappwebview: ^5.7.2
  collection: ^1.16.0
  flutter_rounded_date_picker: ^3.0.2
  floating_snackbar: ^1.0.3+1
  dotted_line: ^3.1.0
  connectivity_plus: ^4.0.1
  internet_file: ^1.2.0
  shimmer: ^3.0.0
  pdfx: ^2.3.0
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^15.1.0+1
  path_provider: ^2.1.0
  firebase_crashlytics: ^3.3.5
  smooth_page_indicator: ^1.1.0

  flutter_localizations:
    sdk: flutter

  here_sdk:
    path: plugins/here_sdk

  # flutter_compass: ^0.7.0
  flutter_compass:
    git: https://github.com/hemanthrajv/flutter_compass.git
  package_info_plus: ^4.1.0
  
dev_dependencies:
  hive_generator: ^1.1.3
  build_runner: ^2.3.0
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: ^2.2.19

  # $ flutter pub run flutter_launcher_icons
  # $ flutter pub run flutter_native_splash:create
  
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  fonts:
    - family: NavikaIcons
      fonts:
        - asset: assets/fonts/NavikaIcons.ttf

    - family: Segoe Ui
      fonts:
        - asset: assets/fonts/Segoe UI.ttf
        - asset: assets/fonts/Segoe UI Bold.ttf
          weight: 700

    - family:  Diode
      fonts:
        - asset: assets/fonts/TransilienSmall.ttf

  assets:
    - assets/ca/lets-encrypt-r3.pem
    
    - assets/img/icons/bus.png
    - assets/img/icons/bus_light.png
    - assets/img/icons/tram_light.png
    - assets/img/icons/cable.png
    - assets/img/icons/metro.png
    - assets/img/icons/cable_light.png
    - assets/img/icons/navette_fluviale.png
    - assets/img/icons/tram.png
    - assets/img/icons/noctilien_light.png
    - assets/img/icons/noctilien.png
    - assets/img/icons/metro_light.png
    - assets/img/icons/navette_fluviale_light.png
    - assets/img/icons/RER_light.png
    - assets/img/icons/train.png
    - assets/img/icons/RER.png
    - assets/img/icons/train_light.png

    - assets/img/icons/lines/CABLE_C1.png
    - assets/img/icons/lines/CABLE_C1_light.png
    - assets/img/icons/lines/METRO_1.png
    - assets/img/icons/lines/METRO_1_light.png
    - assets/img/icons/lines/METRO_2.png
    - assets/img/icons/lines/METRO_2_light.png
    - assets/img/icons/lines/METRO_3.png
    - assets/img/icons/lines/METRO_3_light.png
    - assets/img/icons/lines/METRO_3b.png
    - assets/img/icons/lines/METRO_3b_light.png
    - assets/img/icons/lines/METRO_4.png
    - assets/img/icons/lines/METRO_4_light.png
    - assets/img/icons/lines/METRO_5.png
    - assets/img/icons/lines/METRO_5_light.png
    - assets/img/icons/lines/METRO_6.png
    - assets/img/icons/lines/METRO_6_light.png
    - assets/img/icons/lines/METRO_7.png
    - assets/img/icons/lines/METRO_7_light.png
    - assets/img/icons/lines/METRO_7b.png
    - assets/img/icons/lines/METRO_7b_light.png
    - assets/img/icons/lines/METRO_8.png
    - assets/img/icons/lines/METRO_8_light.png
    - assets/img/icons/lines/METRO_9.png
    - assets/img/icons/lines/METRO_9_light.png
    - assets/img/icons/lines/METRO_10.png
    - assets/img/icons/lines/METRO_10_light.png
    - assets/img/icons/lines/METRO_11.png
    - assets/img/icons/lines/METRO_11_light.png
    - assets/img/icons/lines/METRO_12.png
    - assets/img/icons/lines/METRO_12_light.png
    - assets/img/icons/lines/METRO_13.png
    - assets/img/icons/lines/METRO_13_light.png
    - assets/img/icons/lines/METRO_14.png
    - assets/img/icons/lines/METRO_14_light.png
    - assets/img/icons/lines/METRO_15.png
    - assets/img/icons/lines/METRO_15_light.png
    - assets/img/icons/lines/METRO_16.png
    - assets/img/icons/lines/METRO_16_light.png
    - assets/img/icons/lines/METRO_17.png
    - assets/img/icons/lines/METRO_17_light.png
    - assets/img/icons/lines/METRO_18.png
    - assets/img/icons/lines/METRO_18_light.png
    - assets/img/icons/lines/RER_A.png
    - assets/img/icons/lines/RER_A_light.png
    - assets/img/icons/lines/RER_B.png
    - assets/img/icons/lines/RER_B_light.png
    - assets/img/icons/lines/RER_C.png
    - assets/img/icons/lines/RER_C_light.png
    - assets/img/icons/lines/RER_D.png
    - assets/img/icons/lines/RER_D_light.png
    - assets/img/icons/lines/RER_E.png
    - assets/img/icons/lines/RER_E_light.png
    - assets/img/icons/lines/TRAIN_H.png
    - assets/img/icons/lines/TRAIN_H_light.png
    - assets/img/icons/lines/TRAIN_J.png
    - assets/img/icons/lines/TRAIN_J_light.png
    - assets/img/icons/lines/TRAIN_K.png
    - assets/img/icons/lines/TRAIN_K_light.png
    - assets/img/icons/lines/TRAIN_L.png
    - assets/img/icons/lines/TRAIN_L_light.png
    - assets/img/icons/lines/TRAIN_N.png
    - assets/img/icons/lines/TRAIN_N_light.png
    - assets/img/icons/lines/TRAIN_P.png
    - assets/img/icons/lines/TRAIN_P_light.png
    - assets/img/icons/lines/TRAIN_R.png
    - assets/img/icons/lines/TRAIN_R_light.png
    - assets/img/icons/lines/TRAIN_U.png
    - assets/img/icons/lines/TRAIN_U_light.png
    - assets/img/icons/lines/TRAM_T1.png
    - assets/img/icons/lines/TRAM_T1_light.png
    - assets/img/icons/lines/TRAM_T2.png
    - assets/img/icons/lines/TRAM_T2_light.png
    - assets/img/icons/lines/TRAM_T3a.png
    - assets/img/icons/lines/TRAM_T3a_light.png
    - assets/img/icons/lines/TRAM_T3b.png
    - assets/img/icons/lines/TRAM_T3b_light.png
    - assets/img/icons/lines/TRAM_T4.png
    - assets/img/icons/lines/TRAM_T4_light.png
    - assets/img/icons/lines/TRAM_T5.png
    - assets/img/icons/lines/TRAM_T5_light.png
    - assets/img/icons/lines/TRAM_T6.png
    - assets/img/icons/lines/TRAM_T6_light.png
    - assets/img/icons/lines/TRAM_T7.png
    - assets/img/icons/lines/TRAM_T7_light.png
    - assets/img/icons/lines/TRAM_T8.png
    - assets/img/icons/lines/TRAM_T8_light.png
    - assets/img/icons/lines/TRAM_T9.png
    - assets/img/icons/lines/TRAM_T9_light.png
    - assets/img/icons/lines/TRAM_T10.png
    - assets/img/icons/lines/TRAM_T10_light.png
    - assets/img/icons/lines/TRAM_T11.png
    - assets/img/icons/lines/TRAM_T11_light.png
    - assets/img/icons/lines/TRAM_T12.png
    - assets/img/icons/lines/TRAM_T12_light.png
    - assets/img/icons/lines/TRAM_T13.png
    - assets/img/icons/lines/TRAM_T13_light.png

    - assets/img/icons/noctilien/NOCT_01.png
    - assets/img/icons/noctilien/NOCT_02.png
    - assets/img/icons/noctilien/NOCT_11.png
    - assets/img/icons/noctilien/NOCT_12.png
    - assets/img/icons/noctilien/NOCT_13.png
    - assets/img/icons/noctilien/NOCT_14.png
    - assets/img/icons/noctilien/NOCT_15.png
    - assets/img/icons/noctilien/NOCT_16.png
    - assets/img/icons/noctilien/NOCT_21.png
    - assets/img/icons/noctilien/NOCT_22.png
    - assets/img/icons/noctilien/NOCT_23.png
    - assets/img/icons/noctilien/NOCT_24.png
    - assets/img/icons/noctilien/NOCT_31.png
    - assets/img/icons/noctilien/NOCT_32.png
    - assets/img/icons/noctilien/NOCT_33.png
    - assets/img/icons/noctilien/NOCT_34.png
    - assets/img/icons/noctilien/NOCT_35.png
    - assets/img/icons/noctilien/NOCT_41.png
    - assets/img/icons/noctilien/NOCT_42.png
    - assets/img/icons/noctilien/NOCT_43.png
    - assets/img/icons/noctilien/NOCT_44.png
    - assets/img/icons/noctilien/NOCT_45.png
    - assets/img/icons/noctilien/NOCT_51.png
    - assets/img/icons/noctilien/NOCT_52.png
    - assets/img/icons/noctilien/NOCT_53.png
    - assets/img/icons/noctilien/NOCT_61.png
    - assets/img/icons/noctilien/NOCT_62.png
    - assets/img/icons/noctilien/NOCT_63.png
    - assets/img/icons/noctilien/NOCT_66.png
    - assets/img/icons/noctilien/NOCT_71.png
    - assets/img/icons/noctilien/NOCT_122.png
    - assets/img/icons/noctilien/NOCT_130.png
    - assets/img/icons/noctilien/NOCT_131.png
    - assets/img/icons/noctilien/NOCT_132.png
    - assets/img/icons/noctilien/NOCT_133.png
    - assets/img/icons/noctilien/NOCT_134.png
    - assets/img/icons/noctilien/NOCT_135.png
    - assets/img/icons/noctilien/NOCT_140.png
    - assets/img/icons/noctilien/NOCT_141.png
    - assets/img/icons/noctilien/NOCT_142.png
    - assets/img/icons/noctilien/NOCT_143.png
    - assets/img/icons/noctilien/NOCT_144.png
    - assets/img/icons/noctilien/NOCT_145.png
    - assets/img/icons/noctilien/NOCT_150.png
    - assets/img/icons/noctilien/NOCT_151.png
    - assets/img/icons/noctilien/NOCT_152.png
    - assets/img/icons/noctilien/NOCT_153.png
    - assets/img/icons/noctilien/NOCT_154.png

    - assets/img/icons/sncf/logo_white.png
    - assets/img/icons/sncf/logo_color.png
    - assets/img/icons/sncf/logo.png
    - assets/img/icons/sncf/TER.png
    - assets/img/icons/sncf/TER_white.png
    - assets/img/icons/sncf/TER_color.png

    - assets/img/icons/lines/CDGVAL.png
    - assets/img/icons/lines/ORLYVAL.png
    - assets/img/icons/lines/CDGVAL.png
    - assets/img/icons/lines/ORLYVAL.png

    - assets/img/marker/marker_bike_light.png
    - assets/img/marker/marker_bike.png
    - assets/img/marker/marker_bus.png
    - assets/img/marker/marker_bus_light.png
    - assets/img/marker/marker_cable.png
    - assets/img/marker/marker_cable_light.png
    - assets/img/marker/marker_metro.png
    - assets/img/marker/marker_metro_light.png
    - assets/img/marker/marker_navette_fluviale.png
    - assets/img/marker/marker_navette_fluviale_light.png
    - assets/img/marker/marker_noctilien.png
    - assets/img/marker/marker_noctilien_light.png
    - assets/img/marker/marker_rer.png
    - assets/img/marker/marker_rer_light.png
    - assets/img/marker/marker_train.png
    - assets/img/marker/marker_train_light.png
    - assets/img/marker/marker_tram.png
    - assets/img/marker/marker_tram_light.png
    - assets/img/marker/mini_bike_light.png
    - assets/img/marker/mini.png
    - assets/img/marker/mini_light.png
    - assets/img/marker/mini_bike.png
    
    - assets/img/modal/acces_ufr.png
    - assets/img/modal/acces_ufr_train.png
    - assets/img/modal/alert.png
    - assets/img/modal/alert_white.png
    - assets/img/modal/emergency_call.png
    - assets/img/modal/emergency_signal.png
    - assets/img/modal/error.png
    - assets/img/modal/error_white.png
    - assets/img/modal/futur_work.png
    - assets/img/modal/information.png
    - assets/img/modal/information_white.png
    - assets/img/modal/interogation.png
    - assets/img/modal/interogation_grey.png
    - assets/img/modal/interogation_white.png
    - assets/img/modal/valid.png
    - assets/img/modal/valid_white.png
    - assets/img/modal/warning.png
    - assets/img/modal/work.png
    - assets/img/modal/work_white.png

    - assets/img/sign_top.svg
    - assets/img/bus_schedules.png
    - assets/img/lines.png
    - assets/img/cancel.svg
    - assets/img/maintenance.png
    - assets/img/null.png
    - assets/img/position.png
    - assets/img/sign.svg
    
    - assets/img/cloud_off.svg
    - assets/img/cloud_sad.svg
    - assets/img/cloud_off.png
    - assets/img/cloud_sad.png
    - assets/img/journeys.png

    - assets/img/here/HERE_logo_full.svg
    - assets/img/here/HERE_logo_full_inverted.svg

    - assets/img/maintenance.png

    - assets/img/logo/logo_large.png
    - assets/img/logo/logo.png

    - assets/img/serin/serin_cgt.png
    - assets/img/serin/serin_work.png
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-assets/fonts/#from-packages
